# Import SparkSession from pyspark.sql to initialize our distributed processing engine context.
from pyspark.sql import SparkSession

def run_bronze_ingestion():
    # Initialize or retrieve the active Spark driver session for Databricks with a distinct application name.
    spark = SparkSession.builder.appName("ForYourService-BronzeIngestion").getOrCreate()

    # Define the file path pattern pointing to raw multi-line JSON files generated by our database extraction tool.
    raw_landing_path = "data/bronze/*.json"

    # Read the raw JSON files into a distributed Spark DataFrame, enabling multiline parsing and inferring schema automatically.
    df_raw = spark.read.option("multiline", "true").json(raw_landing_path)

    # Define the target Delta Lake storage path for the Bronze layer tables.
    bronze_table_path = "dbfs:/mnt/lakehouse/bronze/transactions"

    # Write the uncleaned raw DataFrame into Delta format using append mode so historical records are preserved.
    df_raw.write.format("delta").mode("append").save(bronze_table_path)
    
    # Print a confirmation message to standard output indicating successful raw ingestion.
    print(f"Successfully ingested raw records into Bronze Delta table at {bronze_table_path}")

if __name__ == "__main__":
    # Execute the bronze ingestion function when run directly.
    run_bronze_ingestion()
