apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: fys-internal-only
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/default/sa/for-your-service-sa"]
