# Databricks notebook source
# DBTITLE 1,Unity Catalog Setup - For Your Service
# MAGIC %md
# MAGIC # 🗄️ Unity Catalog Setup - For Your Service
# MAGIC ## 7 Eagle Group - Veteran Job Matching Platform
# MAGIC
# MAGIC ---
# MAGIC
# MAGIC ## Purpose
# MAGIC
# MAGIC This notebook creates the Unity Catalog tables required for the Hugging Face API backend.
# MAGIC
# MAGIC **Tables Created:**
# MAGIC 1. `workspace.fys_silver.veteran_profiles` - Veteran intake data
# MAGIC 2. `workspace.fys_bronze.job_postings` - Job listings from scrapers
# MAGIC
# MAGIC ---
# MAGIC
# MAGIC ## Prerequisites
# MAGIC
# MAGIC * Unity Catalog enabled
# MAGIC * `workspace` catalog exists
# MAGIC * Permissions to create schemas and tables
# MAGIC
# MAGIC ---
# MAGIC
# MAGIC Developer: Free Hall <whall4.wh@gmail.com>  
# MAGIC Organization: 7 Eagle Group  
# MAGIC Date: 2026-08-09

# COMMAND ----------

# DBTITLE 1,Create Catalog and Schemas
# MAGIC %sql
# MAGIC -- Create catalog if not exists
# MAGIC CREATE CATALOG IF NOT EXISTS workspace
# MAGIC   COMMENT 'For Your Service - 7 Eagle Group workspace catalog';
# MAGIC
# MAGIC -- Create Bronze schema (raw job postings)
# MAGIC CREATE SCHEMA IF NOT EXISTS workspace.fys_bronze
# MAGIC   COMMENT 'Raw job postings from Indeed scraper';
# MAGIC
# MAGIC -- Create Silver schema (veteran profiles, cleaned data)
# MAGIC CREATE SCHEMA IF NOT EXISTS workspace.fys_silver
# MAGIC   COMMENT 'Veteran profiles and processed data';
# MAGIC
# MAGIC -- Verify schemas
# MAGIC SHOW SCHEMAS IN workspace;

# COMMAND ----------

# DBTITLE 1,Create veteran_profiles Table
# MAGIC %sql
# MAGIC -- Drop if exists (for clean setup)
# MAGIC DROP TABLE IF EXISTS workspace.fys_silver.veteran_profiles;
# MAGIC
# MAGIC -- Create veteran profiles table
# MAGIC CREATE TABLE workspace.fys_silver.veteran_profiles (
# MAGIC   veteran_id STRING NOT NULL COMMENT 'UUID generated by API',
# MAGIC   name STRING NOT NULL COMMENT 'Full name',
# MAGIC   email STRING NOT NULL COMMENT 'Email address',
# MAGIC   target_city STRING COMMENT 'Preferred job location city',
# MAGIC   target_state STRING COMMENT 'Preferred job location state',
# MAGIC   total_years INT COMMENT 'Total years of experience',
# MAGIC   seniority_level STRING COMMENT 'Entry/Mid/Senior/Lead',
# MAGIC   technical_skills STRING COMMENT 'JSON string of skills by proficiency',
# MAGIC   target_roles STRING COMMENT 'JSON string of desired job titles',
# MAGIC   salary_min INT COMMENT 'Minimum acceptable salary',
# MAGIC   salary_max INT COMMENT 'Maximum target salary',
# MAGIC   created_at TIMESTAMP NOT NULL COMMENT 'Profile creation timestamp',
# MAGIC   updated_at TIMESTAMP NOT NULL COMMENT 'Last update timestamp',
# MAGIC   CONSTRAINT veteran_profiles_pk PRIMARY KEY (veteran_id)
# MAGIC )
# MAGIC USING DELTA
# MAGIC COMMENT 'Veteran profiles from Base44 intake form'
# MAGIC TBLPROPERTIES (
# MAGIC   'delta.enableChangeDataFeed' = 'true',
# MAGIC   'delta.autoOptimize.optimizeWrite' = 'true',
# MAGIC   'delta.autoOptimize.autoCompact' = 'true'
# MAGIC );
# MAGIC
# MAGIC -- Add governance tags
# MAGIC ALTER TABLE workspace.fys_silver.veteran_profiles 
# MAGIC   SET TAGS ('pii' = 'true', 'domain' = 'veteran_services');
# MAGIC
# MAGIC -- Show table details
# MAGIC DESCRIBE EXTENDED workspace.fys_silver.veteran_profiles;

# COMMAND ----------

# DBTITLE 1,Create job_postings Table
# MAGIC %sql
# MAGIC -- Drop if exists (for clean setup)
# MAGIC DROP TABLE IF EXISTS workspace.fys_bronze.job_postings;
# MAGIC
# MAGIC -- Create job postings table
# MAGIC CREATE TABLE workspace.fys_bronze.job_postings (
# MAGIC   job_id STRING NOT NULL COMMENT 'Unique job identifier',
# MAGIC   title STRING NOT NULL COMMENT 'Job title',
# MAGIC   company STRING NOT NULL COMMENT 'Company name',
# MAGIC   location_city STRING COMMENT 'Job location city',
# MAGIC   location_state STRING COMMENT 'Job location state',
# MAGIC   location_display STRING COMMENT 'Full location string',
# MAGIC   salary_min DOUBLE COMMENT 'Minimum salary',
# MAGIC   salary_max DOUBLE COMMENT 'Maximum salary',
# MAGIC   salary_display STRING COMMENT 'Salary as displayed in posting',
# MAGIC   description STRING COMMENT 'Full job description',
# MAGIC   requirements STRING COMMENT 'Job requirements',
# MAGIC   benefits STRING COMMENT 'Benefits offered',
# MAGIC   url STRING COMMENT 'Job posting URL',
# MAGIC   source STRING COMMENT 'Data source (indeed, linkedin, etc)',
# MAGIC   scraped_at TIMESTAMP COMMENT 'When job was scraped',
# MAGIC   created_at TIMESTAMP NOT NULL COMMENT 'Record creation timestamp',
# MAGIC   CONSTRAINT job_postings_pk PRIMARY KEY (job_id)
# MAGIC )
# MAGIC USING DELTA
# MAGIC COMMENT 'Raw job postings from Indeed and other sources'
# MAGIC TBLPROPERTIES (
# MAGIC   'delta.enableChangeDataFeed' = 'true',
# MAGIC   'delta.autoOptimize.optimizeWrite' = 'true',
# MAGIC   'delta.autoOptimize.autoCompact' = 'true'
# MAGIC );
# MAGIC
# MAGIC -- Add governance tags
# MAGIC ALTER TABLE workspace.fys_bronze.job_postings 
# MAGIC   SET TAGS ('domain' = 'job_market', 'source' = 'web_scraper');
# MAGIC
# MAGIC -- Show table details
# MAGIC DESCRIBE EXTENDED workspace.fys_bronze.job_postings;

# COMMAND ----------

# DBTITLE 1,Insert Sample Data - Test Veteran Profile
# MAGIC %sql
# MAGIC -- Insert Free Hall's profile as test data
# MAGIC INSERT INTO workspace.fys_silver.veteran_profiles VALUES (
# MAGIC   'test-veteran-001',
# MAGIC   'Free Hall',
# MAGIC   'whall4.wh@gmail.com',
# MAGIC   'Greenville',
# MAGIC   'SC',
# MAGIC   18, -- Years of experience (Army 1999-2017)
# MAGIC   'Senior',
# MAGIC   '{"expert": ["AWS", "Azure", "Kubernetes", "Docker", "Terraform"], "proficient": ["Python", "Bash", "Jenkins", "GitHub"], "familiar": ["GCP", "Ansible"]}',
# MAGIC   '["DevOps Engineer", "Solutions Architect", "Cloud Engineer", "Site Reliability Engineer", "Platform Engineer"]',
# MAGIC   120000,
# MAGIC   180000,
# MAGIC   current_timestamp(),
# MAGIC   current_timestamp()
# MAGIC );
# MAGIC
# MAGIC -- Verify insert
# MAGIC SELECT * FROM workspace.fys_silver.veteran_profiles;

# COMMAND ----------

# DBTITLE 1,Insert Sample Data - Houston Jobs (Test Data)
# MAGIC %sql
# MAGIC -- Insert sample Houston jobs (from existing scraper data)
# MAGIC -- Note: We have 90 Houston jobs in the system already from Indeed scraper
# MAGIC
# MAGIC INSERT INTO workspace.fys_bronze.job_postings 
# MAGIC SELECT 
# MAGIC   job_id,
# MAGIC   title,
# MAGIC   company,
# MAGIC   location.city as location_city,
# MAGIC   location.state as location_state,
# MAGIC   location.display as location_display,
# MAGIC   salary.min as salary_min,
# MAGIC   salary.max as salary_max,
# MAGIC   salary.display as salary_display,
# MAGIC   description,
# MAGIC   requirements,
# MAGIC   benefits,
# MAGIC   url,
# MAGIC   'indeed' as source,
# MAGIC   scraped_at,
# MAGIC   current_timestamp() as created_at
# MAGIC FROM workspace.fys_bronze.indeed_jobs_bronze
# MAGIC WHERE location.city = 'Houston' AND location.state = 'TX'
# MAGIC LIMIT 100;
# MAGIC
# MAGIC -- Show sample
# MAGIC SELECT job_id, title, company, location_display, salary_display 
# MAGIC FROM workspace.fys_bronze.job_postings 
# MAGIC LIMIT 10;

# COMMAND ----------

# DBTITLE 1,Verify Tables and Grant Permissions
# MAGIC %sql
# MAGIC -- Show all tables in both schemas
# MAGIC SHOW TABLES IN workspace.fys_bronze;
# MAGIC SHOW TABLES IN workspace.fys_silver;
# MAGIC
# MAGIC -- Count records
# MAGIC SELECT 'veteran_profiles' as table_name, COUNT(*) as record_count 
# MAGIC FROM workspace.fys_silver.veteran_profiles
# MAGIC UNION ALL
# MAGIC SELECT 'job_postings' as table_name, COUNT(*) as record_count 
# MAGIC FROM workspace.fys_bronze.job_postings;
# MAGIC
# MAGIC -- Grant read permissions to API service principal (update with actual principal)
# MAGIC -- GRANT SELECT ON TABLE workspace.fys_silver.veteran_profiles TO `api-service-principal`;
# MAGIC -- GRANT SELECT ON TABLE workspace.fys_bronze.job_postings TO `api-service-principal`;
# MAGIC -- GRANT MODIFY ON TABLE workspace.fys_silver.veteran_profiles TO `api-service-principal`;

# COMMAND ----------

# DBTITLE 1,Setup Complete - Summary
# MAGIC %md
# MAGIC ## ✅ Setup Complete
# MAGIC
# MAGIC ### Tables Created:
# MAGIC
# MAGIC 1. **workspace.fys_silver.veteran_profiles**
# MAGIC    * Primary Key: veteran_id
# MAGIC    * Sample Record: Free Hall (test-veteran-001)
# MAGIC    * Delta features: CDC, Auto-optimize enabled
# MAGIC    * Tags: pii=true, domain=veteran_services
# MAGIC
# MAGIC 2. **workspace.fys_bronze.job_postings**
# MAGIC    * Primary Key: job_id
# MAGIC    * Sample Records: Houston, TX jobs (from Indeed scraper)
# MAGIC    * Delta features: CDC, Auto-optimize enabled
# MAGIC    * Tags: domain=job_market, source=web_scraper
# MAGIC
# MAGIC ---
# MAGIC
# MAGIC ### Next Steps:
# MAGIC
# MAGIC 1. **Generate Databricks Token** for Hugging Face API
# MAGIC    * User Settings → Developer → Access Tokens
# MAGIC    * Set 90-day lifetime
# MAGIC    * Copy token (starts with `dapi...`)
# MAGIC
# MAGIC 2. **Configure Hugging Face Secrets**
# MAGIC    * Add DATABRICKS_TOKEN to HF Space secrets
# MAGIC
# MAGIC 3. **Test API Endpoints**
# MAGIC    * POST /api/v1/veteran/register
# MAGIC    * GET /api/v1/veteran/{id}
# MAGIC    * POST /api/v1/match
# MAGIC    * GET /api/v1/jobs
# MAGIC
# MAGIC ---
# MAGIC
# MAGIC **Developer:** Free Hall <whall4.wh@gmail.com>  
# MAGIC **Organization:** 7 Eagle Group  
# MAGIC **Status:** Ready for API integration

# COMMAND ----------

